
NAME: Experiment

GENERAL:
  torch_seed: 10
  device: 'cuda:0'
  save_dir: 'figs/test'

DATASET:
  name: 'mnistdigits_grid2patch'
  img_size: 32
  num_samples_train: 600
  delta: 0.000001
  batch_size_train: 32
  img_channels: 1

TRAIN:
  epochs: 10
  m_inc_proc: 'inc_1_after_60_interval_10'
  show_results_epoch: 1
  train_model_iter: 1
  train_H_iter: 1
  criterion: 'nn.L1Loss().to(device)'  
  classifier: None
  rescale_for_classifier: None


MODEL:
  MODEL_H:
    T: 5
    H_weight_preprocess: 'ifft_2d_with_fftshift_real'
    H_init: 'fft'
    initialization_bias: 0
    H_activation: 'sigmoid_custom'
    lr_H: 100.0

  MODEL_A:
    sPSF: 'get_gaussian(side_len=5, s=1)'
    exPSF: 'get_gaussian(side_len=5, s=1)'
    noise: True
    lambda_scale_factor: 1
    rotation_lambda: 1000.0
    shift_lambda_real: 0.0
    readnoise_std: 0.0

  MODEL_DECODER:
    name: 'genv1'
    upsample_net: 'bicubic_interp'
    custom_upsampling_bias: True
    upsample_net_init_method: 'randn'
    channel_list: [4, 3, 2]
    lr_decoder: 0.001
    last_activation: None
    connect_forward_inverse: 'no_skips'
